#!/bin/bash
# Package ChatRoomClient for Windows
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
BUILD_DIR="$PROJECT_DIR/build-windows"
QT_DIR="/opt/qt6-windows/6.2.4/mingw_64"
PKG_NAME="ChatRoom-Client-windows-x64-v1.0.0"
PKG_DIR="$PROJECT_DIR/release/$PKG_NAME"

echo "=== Packaging ChatRoomClient for Windows ==="

# Clean package directory
rm -rf "$PKG_DIR"
mkdir -p "$PKG_DIR"/{bin,plugins/{platforms,sqldrivers,styles,imageformats,iconengines,tls},qml}

# 1. Copy the executable
cp "$BUILD_DIR/client/ChatRoomClient.exe" "$PKG_DIR/bin/"
echo "[1/5] Copied ChatRoomClient.exe"

# 2. Copy Qt6 DLLs (only the ones needed)
DLLS=(
    Qt6Core.dll
    Qt6Gui.dll
    Qt6Network.dll
    Qt6Sql.dll
    Qt6Qml.dll
    Qt6QmlCore.dll
    Qt6QmlModels.dll
    Qt6QmlWorkerScript.dll
    Qt6Quick.dll
    Qt6QuickControls2.dll
    Qt6QuickControls2Impl.dll
    Qt6QuickLayouts.dll
    Qt6QuickTemplates2.dll
    Qt6OpenGL.dll
    Qt6Widgets.dll
    Qt6LabsAnimation.dll
    Qt6LabsFolderListModel.dll
    Qt6LabsQmlModels.dll
    Qt6LabsSettings.dll
    Qt6ShaderTools.dll
    Qt6QuickShapes.dll
    Qt6QuickDialogs2.dll
    Qt6QuickDialogs2QuickImpl.dll
    Qt6QuickDialogs2Utils.dll
    libgcc_s_seh-1.dll
    libstdc++-6.dll
    libwinpthread-1.dll
    d3dcompiler_47.dll
)

for dll in "${DLLS[@]}"; do
    if [ -f "$QT_DIR/bin/$dll" ]; then
        cp "$QT_DIR/bin/$dll" "$PKG_DIR/bin/"
    else
        echo "  WARNING: $dll not found in Qt distribution"
    fi
done
echo "[2/5] Copied $(ls "$PKG_DIR/bin/"*.dll | wc -l) DLLs"

# 3. Copy Qt plugins
# Platform plugin (essential)
cp "$QT_DIR/plugins/platforms/qwindows.dll" "$PKG_DIR/plugins/platforms/"

# SQLite driver
cp "$QT_DIR/plugins/sqldrivers/qsqlite.dll" "$PKG_DIR/plugins/sqldrivers/"

# Styles
[ -f "$QT_DIR/plugins/styles/qwindowsvistastyle.dll" ] && \
    cp "$QT_DIR/plugins/styles/qwindowsvistastyle.dll" "$PKG_DIR/plugins/styles/"

# Image formats
for f in qico.dll qjpeg.dll qsvg.dll qgif.dll; do
    [ -f "$QT_DIR/plugins/imageformats/$f" ] && \
        cp "$QT_DIR/plugins/imageformats/$f" "$PKG_DIR/plugins/imageformats/"
done

# Icon engines
[ -f "$QT_DIR/plugins/iconengines/qsvgicon.dll" ] && \
    cp "$QT_DIR/plugins/iconengines/qsvgicon.dll" "$PKG_DIR/plugins/iconengines/"

# TLS backend
[ -f "$QT_DIR/plugins/tls/qopensslbackend.dll" ] && \
    cp "$QT_DIR/plugins/tls/qopensslbackend.dll" "$PKG_DIR/plugins/tls/"

echo "[3/5] Copied Qt plugins"

# 4. Copy QML modules
QML_MODULES=(
    QtQuick
    QtQuick/Controls
    QtQuick/Controls/impl
    QtQuick/Controls/Basic
    QtQuick/Controls/Basic/impl
    QtQuick/Controls/Windows
    QtQuick/Layouts
    QtQuick/Window
    QtQml
    QtQml/Models
    QtQml/WorkerScript
    QtCore
    Qt/labs/animation
    Qt/labs/folderlistmodel
    Qt/labs/settings
)

for mod in "${QML_MODULES[@]}"; do
    if [ -d "$QT_DIR/qml/$mod" ]; then
        mkdir -p "$PKG_DIR/qml/$(dirname "$mod")"
        cp -r "$QT_DIR/qml/$mod" "$PKG_DIR/qml/$mod"
    else
        echo "  WARNING: QML module '$mod' not found"
    fi
done

# Copy ChatRoom QML module (generated by build)
if [ -d "$BUILD_DIR/client/ChatRoom" ]; then
    cp -r "$BUILD_DIR/client/ChatRoom" "$PKG_DIR/qml/"
    echo "  Copied ChatRoom QML module from build"
fi

echo "[4/5] Copied QML modules"

# 5. Create start_client.bat
cat > "$PKG_DIR/start_client.bat" << 'BAT'
@echo off
chcp 65001 >nul 2>&1
cd /d "%~dp0"
set PATH=%~dp0bin;%PATH%
set QT_PLUGIN_PATH=%~dp0plugins
set QML2_IMPORT_PATH=%~dp0qml
bin\ChatRoomClient.exe
if errorlevel 1 pause
BAT

# Create README.txt
cat > "$PKG_DIR/README.txt" << 'EOF'
ChatRoom Client v1.0.0 - Windows x64

Requirements:
  - Windows 10/11 (x64)
  - No additional runtime installation needed

Usage:
  Double-click start_client.bat to launch
  Or run: bin\ChatRoomClient.exe

Default server: localhost:8080
EOF

echo "[5/5] Created start_client.bat and README.txt"

# Show package size
echo ""
echo "=== Package Summary ==="
du -sh "$PKG_DIR"
find "$PKG_DIR" -type f | wc -l
echo "files total"
echo ""
echo "Package directory: $PKG_DIR"
